version: "3.1"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.2
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    broker:
        image: bitnami/kafka:latest
        container_name: broker
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
            KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
            KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
            KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        extra_hosts:
            - "prometheus:127.0.0.1"

    # prometheus:
    #     image: prom/prometheus:latest
    #     container_name: prometheus
    #     ports:
    #         - "9090:9090"
    #     command:
    #         - "--config.file=/etc/prometheus/prometheus.yml"
    #     volumes:
    #         - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

    # broker:
    #     image: confluentinc/cp-kafka:7.3.2
    #     container_name: broker
    #     depends_on:
    #         - zookeeper
    #     ports:
    #         - "9092:9092"
    #     environment:
    #         KAFKA_BROKER_ID: 1
    #         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    #         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
    #         KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #         KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    #         KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
